/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function startAudioCapture(callback: (...args: any[]) => any): void
export declare function stopAudioCapture(): void
